"""
Analyze body poses/actions generated by BodyDirector + BodyAgent.

Use this after pipeline changes to get concrete feedback on:
  - sitting / walking base posture strength
  - action keyframe motion magnitude
  - missing bones, weak gestures, asymmetric issues
  - end-to-end director → bone packet quality

Run:
  python tools/analyze_body_poses.py
  python tools/analyze_body_poses.py --out temp/body_pose_report.json

Exit code 1 if critical issues found.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from face_agents.body_agent import (  # noqa: E402
    ACTION_CLIPS,
    BASE_STATE_POSES,
    BodyAgent,
    _sample_action,
)
from face_agents.body_director_agent import BodyDirectorAgent  # noqa: E402
from face_agents.director_schema import BODY_STATES  # noqa: E402

BASE_BONES = {
    "pelvis", "spine1", "left_hip", "right_hip", "left_knee", "right_knee",
    "left_ankle", "right_ankle", "left_foot", "right_foot",
}
UPPER_BONES_HINT = {
    "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
    "left_wrist", "right_wrist", "spine2", "spine3", "neck", "head",
}


class _Ctx:
    def __init__(
        self,
        actions: List[str],
        state: str = "standing",
        gesture: str = "none",
        emotion: str = "neutral",
        intensity: float = 0.85,
        duration: float = 2.5,
        t: float = 0.5,
        speaking: bool = True,
        energy: float = 0.4,
    ):
        self.t = t
        self.duration = duration
        self.emotion = emotion
        self.intensity = intensity
        self.is_speaking = speaking
        self.extras = {
            "body_actions": actions,
            "action_timing": "start",
            "gesture_target": gesture,
            "hand": "right",
            "body_state": state,
            "state": state,
        }
        self._energy = energy

    def speech_energy(self) -> float:
        return self._energy if self.is_speaking else 0.0


def _mag(eul: Dict[str, float]) -> float:
    return math.sqrt(
        (eul.get("x", 0) or 0) ** 2
        + (eul.get("y", 0) or 0) ** 2
        + (eul.get("z", 0) or 0) ** 2
    )


def _pose_stats(bones: Dict[str, Any]) -> Dict[str, Any]:
    mags = {k: _mag(v) for k, v in bones.items() if isinstance(v, dict)}
    total = sum(mags.values())
    base_m = sum(m for k, m in mags.items() if k in BASE_BONES)
    upper_m = sum(m for k, m in mags.items() if k not in BASE_BONES)
    top = sorted(mags.items(), key=lambda kv: -kv[1])[:8]
    return {
        "bone_count": len(mags),
        "total_magnitude": round(total, 4),
        "base_magnitude": round(base_m, 4),
        "upper_magnitude": round(upper_m, 4),
        "top_bones": [{ "name": n, "mag": round(m, 4) } for n, m in top],
        "has_sit_chain": all(
            k in mags for k in ("pelvis", "left_hip", "right_hip", "left_knee", "right_knee")
        ),
    }


def analyze_action(name: str) -> Dict[str, Any]:
    clip = ACTION_CLIPS.get(name) or {}
    dur = float(clip.get("duration", 1.0))
    samples = []
    peak = 0.0
    peak_t = 0.0
    for i in range(0, 11):
        t = (i / 10.0) * dur
        pose = _sample_action(name, t, dur, intensity=0.9)
        st = _pose_stats(pose)
        samples.append({"t": round(t, 3), **st})
        if st["total_magnitude"] > peak:
            peak = st["total_magnitude"]
            peak_t = t
    issues = []
    # idle / look_camera intentionally near-zero (rest or tiny neck)
    intentional_rest = name in ("idle", "look_camera")
    if not intentional_rest:
        if peak < 0.15:
            issues.append(f"WEAK: peak motion {peak:.3f} < 0.15 — may look idle")
        if peak < 0.05:
            issues.append("CRITICAL: almost no motion")
        mid_check = samples[5] if len(samples) > 5 else samples[-1]
        if mid_check["bone_count"] == 0:
            issues.append("CRITICAL: mid-clip has zero bones")
    mid = samples[5] if len(samples) > 5 else samples[-1]
    return {
        "action": name,
        "duration": dur,
        "loop": bool(clip.get("loop")),
        "peak_magnitude": round(peak, 4),
        "peak_t": round(peak_t, 3),
        "mid": mid,
        "issues": issues,
    }


def analyze_state(state: str) -> Dict[str, Any]:
    ba = BodyAgent()
    ctx = _Ctx(actions=["talk_open"], state=state, t=0.6)
    ba.prepare(ctx)
    # sample a few times for walking cycle
    samples = []
    for t in (0.0, 0.3, 0.6, 0.9, 1.2):
        ctx.t = t
        bones = ba.get_body(ctx)
        samples.append({"t": t, **_pose_stats(bones)})
    issues = []
    if state == "sitting":
        s0 = samples[2]
        if not s0["has_sit_chain"]:
            issues.append("CRITICAL: sitting missing hip/knee/pelvis chain")
        if s0["base_magnitude"] < 1.5:
            issues.append(
                f"WEAK sit: base_magnitude={s0['base_magnitude']} "
                "(expect hips+knees bent, usually > 2.0)"
            )
        # hips should be largely flexed (negative x large mag)
        bones = ba.get_body(ctx)
        lh = abs((bones.get("left_hip") or {}).get("x", 0))
        if lh < 0.8:
            issues.append(f"CRITICAL: left_hip.x only {lh:.2f} — sit won't look seated")
    if state == "walking":
        mags = [s["base_magnitude"] for s in samples]
        if max(mags) - min(mags) < 0.05:
            issues.append("WEAK walk: base magnitude barely changes over time (no cycle?)")
        if max(mags) < 0.3:
            issues.append("CRITICAL: walking base motion too small")
    if state == "standing":
        if samples[2]["base_magnitude"] > 0.5:
            issues.append("standing base unexpectedly large")
    return {
        "state": state,
        "samples": samples,
        "issues": issues,
    }


def analyze_director_phrases() -> Dict[str, Any]:
    bd = BodyDirectorAgent(None)
    phrases = [
        "say hello while sitting",
        "walk over and think with hand on chin",
        "while sitting, tell them that is disgusting",
        "say something while sitting",
        "wave and say welcome",
        "stand up and shrug",
        "I am so angry about this",
        "that makes me really sad",
    ]
    rows = []
    issues = []
    for p in phrases:
        beat = bd.direct(p)[0]
        ba = BodyAgent()
        ctx = _Ctx(
            actions=list(beat.get("actions") or []),
            state=str(beat.get("state") or "standing"),
            gesture=str(beat.get("gesture_target") or "none"),
            emotion=str(beat.get("emotion") or "neutral"),
            intensity=float(beat.get("intensity") or 0.7),
            t=0.55,
        )
        ba.prepare(ctx)
        bones = ba.get_body(ctx)
        st = _pose_stats(bones)
        row = {
            "phrase": p,
            "beat": {
                "text": beat.get("text"),
                "state": beat.get("state"),
                "gesture_target": beat.get("gesture_target"),
                "hand": beat.get("hand"),
                "emotion": beat.get("emotion"),
                "actions": beat.get("actions"),
            },
            "pose": st,
        }
        rows.append(row)
        # expectations
        if "sitting" in p and beat.get("state") != "sitting":
            issues.append(f"DIR: '{p}' expected state=sitting got {beat.get('state')}")
        if "sitting" in p and st["base_magnitude"] < 1.0:
            issues.append(f"POSE: '{p}' sitting but weak base mag={st['base_magnitude']}")
        if "chin" in p and beat.get("gesture_target") not in ("chin",):
            issues.append(f"DIR: '{p}' expected gesture chin got {beat.get('gesture_target')}")
        if "wave" in p and "wave" not in (beat.get("actions") or []):
            issues.append(f"DIR: '{p}' expected wave action")
        if st["total_magnitude"] < 0.08 and "stand" not in p:
            issues.append(f"POSE: '{p}' total motion nearly zero")
        # dialogue quality: should not be raw stage direction
        txt = (beat.get("text") or "").lower()
        if "stand up and shrug" in txt or txt.startswith("while sitting"):
            issues.append(f"DIALOGUE: '{p}' still speaking stage direction: {beat.get('text')!r}")
        # emotion-body coupling: angry should have spine/shoulder energy
        if beat.get("emotion") == "angry" and st["upper_magnitude"] < 0.8:
            issues.append(f"EMOTION: angry upper body too soft mag={st['upper_magnitude']}")
        if beat.get("emotion") == "sad" and st["upper_magnitude"] < 0.4:
            issues.append(f"EMOTION: sad body language missing mag={st['upper_magnitude']}")
        # wave realism: needs counterbalance or spine
        if "wave" in (beat.get("actions") or []):
            names = {b["name"] for b in st["top_bones"]}
            if "left_shoulder" not in names and "spine3" not in names and "pelvis" not in names:
                issues.append(f"QUALITY: wave lacks counterbalance bones in top set")
    return {"phrases": rows, "issues": issues}


def analyze_emotion_body() -> Dict[str, Any]:
    """Emotion underlay should create distinct body signatures."""
    ba = BodyAgent()
    rows = []
    issues = []
    for emo in ("happy", "sad", "angry", "surprised", "disgusted", "fearful", "thinking"):
        ctx = _Ctx(actions=["talk_open"], state="standing", emotion=emo, intensity=0.9, t=0.5)
        ba.prepare(ctx)
        bones = ba.get_body(ctx)
        st = _pose_stats(bones)
        rows.append({"emotion": emo, "pose": st})
        if st["upper_magnitude"] < 0.5 and emo != "thinking":
            issues.append(f"EMOTION {emo}: weak body underlay upper={st['upper_magnitude']}")
        if emo == "sad":
            # expect forward spine flex (positive x on spine)
            sp = (bones.get("spine2") or {}).get("x", 0)
            if sp < 0.05:
                issues.append(f"EMOTION sad: spine2.x={sp:.3f} expected forward slump > 0.05")
        if emo == "angry":
            sp = (bones.get("spine3") or {}).get("x", 0)
            if sp > -0.02:
                issues.append(f"EMOTION angry: spine3.x={sp:.3f} expected lean-in (negative)")
    return {"emotions": rows, "issues": issues}


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyze body pose/action generation")
    ap.add_argument(
        "--out",
        type=Path,
        default=ROOT / "temp" / "body_pose_report.json",
        help="JSON report path",
    )
    args = ap.parse_args()

    print("=" * 60)
    print("BODY POSE / ACTION ANALYZER")
    print("=" * 60)

    report: Dict[str, Any] = {
        "base_states_defined": list(BASE_STATE_POSES.keys()),
        "actions": [],
        "states": [],
        "director": {},
        "summary_issues": [],
        "critical": [],
        "warnings": [],
    }

    # Actions
    print("\n--- Actions ---")
    for name in sorted(ACTION_CLIPS.keys()):
        a = analyze_action(name)
        report["actions"].append(a)
        flag = "OK"
        if any("CRITICAL" in i for i in a["issues"]):
            flag = "CRIT"
            report["critical"].extend([f"action:{name}: {i}" for i in a["issues"]])
        elif a["issues"]:
            flag = "WARN"
            report["warnings"].extend([f"action:{name}: {i}" for i in a["issues"]])
        print(
            f"  [{flag:4}] {name:16} peak={a['peak_magnitude']:.3f} "
            f"@t={a['peak_t']:.2f} bones@mid={a['mid']['bone_count']}"
        )
        for i in a["issues"]:
            print(f"           → {i}")

    # States
    print("\n--- Base states (via BodyAgent packet) ---")
    for state in sorted(BODY_STATES):
        s = analyze_state(state)
        report["states"].append(s)
        flag = "OK"
        if any("CRITICAL" in i for i in s["issues"]):
            flag = "CRIT"
            report["critical"].extend([f"state:{state}: {i}" for i in s["issues"]])
        elif s["issues"]:
            flag = "WARN"
            report["warnings"].extend([f"state:{state}: {i}" for i in s["issues"]])
        mid = s["samples"][2]
        print(
            f"  [{flag:4}] {state:10} base_mag={mid['base_magnitude']:.3f} "
            f"upper={mid['upper_magnitude']:.3f} bones={mid['bone_count']} "
            f"sit_chain={mid['has_sit_chain']}"
        )
        for i in s["issues"]:
            print(f"           → {i}")

    # Director phrases
    print("\n--- Director → pose E2E ---")
    d = analyze_director_phrases()
    report["director"] = d
    for row in d["phrases"]:
        b = row["beat"]
        p = row["pose"]
        print(
            f"  '{row['phrase'][:48]}'"
            f"\n      → state={b['state']} gest={b['gesture_target']}/{b['hand']} "
            f"acts={b['actions']}"
            f"\n      → say={b['text']!r}"
            f"\n      → mag base={p['base_magnitude']:.2f} upper={p['upper_magnitude']:.2f} "
            f"n={p['bone_count']}"
        )
    for i in d["issues"]:
        if "CRITICAL" in i or i.startswith("POSE") and "weak" in i.lower():
            report["critical"].append(i)
        else:
            report["warnings"].append(i)
        print(f"  !! {i}")

    # Emotion body underlay
    print("\n--- Emotion body language ---")
    emo_rep = analyze_emotion_body()
    report["emotion_body"] = emo_rep
    for row in emo_rep["emotions"]:
        p = row["pose"]
        print(
            f"  {row['emotion']:12} upper={p['upper_magnitude']:.2f} "
            f"base={p['base_magnitude']:.2f} n={p['bone_count']} "
            f"top={[b['name'] for b in p['top_bones'][:4]]}"
        )
    for i in emo_rep["issues"]:
        report["warnings"].append(i)
        print(f"  !! {i}")

    # Heuristic tips
    print("\n--- Feedback (how to fix) ---")
    tips = []
    if any("sitting" in c for c in report["critical"]):
        tips.append(
            "SITTING: ensure body_agent BASE_STATE_POSES.sitting ships pelvis+hips+knees "
            "and viewer applyBaseStateProcedural + applyBaseBonesFromPacket both run."
        )
    weak_actions = [
        a["action"] for a in report["actions"]
        if a["peak_magnitude"] < 0.25 and a["action"] not in ("idle", "look_camera")
    ]
    if weak_actions:
        tips.append(
            f"WEAK ACTIONS {weak_actions[:6]}: raise peak euler magnitudes in ACTION_CLIPS."
        )
    if any("EMOTION" in w for w in report["warnings"]):
        tips.append("Tune EMOTION_UNDERLAY poses in body_agent.py for weak emotions.")
    if not report["critical"] and not report["warnings"]:
        tips.append("Analyzer clean — hard-refresh viewer and retest sit/wave/angry live.")
    tips.append(
        "Browser: console should show [body_agent] Ready state=… ; Ctrl+Shift+R after HTML changes."
    )
    report["tips"] = tips
    for t in tips:
        print(f"  • {t}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\nReport written: {args.out}")
    print(
        f"Summary: {len(report['critical'])} critical, "
        f"{len(report['warnings'])} warnings"
    )
    print("=" * 60)
    return 1 if report["critical"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
